# Generated by Django 3.2.3 on 2021-06-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Portfolio_site',
            new_name='portfolio_site',
        ),
    ]
